WarehouseClient/WarehouseClient/Models/Shipment.cs
using System;
using System.Collections.Generic;

namespace WarehouseClient.Models
{
    public partial class Shipment
    {
        public int ShipmentId { get; set; }
        public int SellerId { get; set; }
        public int ProductId { get; set; }
        public string ToLocation { get; set; }
        public int Quantity { get; set; }
        public string Status { get; set; }
    }
}

WarehouseClient/WarehouseClient/Controllers/ShipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WarehouseClient.Helper;
using WarehouseClient.Models;

namespace WarehouseClient.Controllers
{
    public class ShipmentController : Controller
    {
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ShipmentController));

        public async Task<IActionResult> Index()
        {
            try
            {
                _log4net.Info("ShipmentController List of Shipment Successfull");
                var shipment = new List<Shipment>();
                using (var httpclient = new HttpClient())
                {
                    httpclient.BaseAddress = new Uri("https://localhost:44301/");
                    HttpResponseMessage res = await httpclient.GetAsync("api/Shipment");
                    if (res.IsSuccessStatusCode)
                    {
                        var results = res.Content.ReadAsStringAsync().Result;
                        shipment = JsonConvert.DeserializeObject<List<Shipment>>(results);
                    }
                }
                return View(shipment);
            }

            catch (Exception ex)
            {
                _log4net.Info("ShipmentController List of Shipment Failed");
                return BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                _log4net.Info("ShipmentController Shipment By ID is Successfull");
                var shipment = new Shipment();
                using(var httpclient = new HttpClient())
                {
                    httpclient.BaseAddress = new Uri("https://localhost:44301/");
                    HttpResponseMessage res = await httpclient.GetAsync($"api/Shipment/{id}");
                    if (res.IsSuccessStatusCode)
                    {
                        var results = res.Content.ReadAsStringAsync().Result;
                        shipment = JsonConvert.DeserializeObject<Shipment>(results);
                    }
                    return View(shipment);
                }
                
            }
            catch (Exception ex)
            {
                _log4net.Info("ShipmentController Shipment by ID Failed");
                return BadRequest(ex.Message);
            }
        }
        public ActionResult Add()
        {
            _log4net.Info("ShipmentController Trying to Add Shipment");
            return View();
        }
        [HttpPost]
        public IActionResult Add(Shipment shipment)
        {
            try
            {
                _log4net.Info("ShipmentController Shipment Successfully Added");
                using (var httpclient = new HttpClient())
                {
                    httpclient.BaseAddress = new Uri("https://localhost:44301/");
                    var postTask = httpclient.PostAsJsonAsync<Shipment>("api/shipment", shipment);

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    return View(shipment);
                }
            }
            catch(Exception ex)
            {
                _log4net.Info("ShipmentController Shipment cannot be Added");
                return BadRequest(ex.Message);
            }
        }
        public IActionResult Delete(int id)
        {
            try
            {
                _log4net.Info("ShipmentController Deleting Shipment");
                using (var httpclient = new HttpClient())
                {
                    httpclient.BaseAddress = new Uri("https://localhost:44301/");
                    var delete = httpclient.DeleteAsync("/api/Shipment?id=" + id);
                    var res = delete.Result;
                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                _log4net.Info("ShipmentController Shipment Deletion Failed");
                return BadRequest(ex.Message);
            }
        }
    }
}

WarehouseClient/WarehouseClient/Views/Shipment/Add.cshtml
@model WarehouseClient.Models.Shipment

@{
    ViewData["Title"] = "Shipment Add";
}

<h1>Place Order</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SellerId" class="control-label"></label>
                <input asp-for="SellerId" class="form-control" />
                <span asp-validation-for="SellerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToLocation" class="control-label"></label>
                <input asp-for="ToLocation" class="form-control" />
                <span asp-validation-for="ToLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Place Order" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WarehouseClient/WarehouseClient/Views/Shipment/Details.cshtml
@model WarehouseClient.Models.Shipment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Shipment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipmentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SellerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SellerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

WarehouseClient/WarehouseClient/Views/Shipment/Index.cshtml
@model IEnumerable<WarehouseClient.Models.Shipment>

@{
    ViewData["Title"] = "Index";
}

<h1>List of Shipment</h1>

<p>
    <a asp-controller="Shipment" asp-action="Add">Place Orders</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShipmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SellerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ShipmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SellerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {  id=item.ShipmentId  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.ShipmentId })
            </td>
        </tr>
}
    </tbody>
</table>